[app.logger]
file = true
console = false
level = 10

[app.setup]
term_colors = true

[app.server]
token = "Zb!2ku&eA2I6f&eP$s1lRIwj01mu9LU8"
server_ip = "127.0.0.1" # Choose any from 127.0.0.0/8
server_port = 1060
server_timeout = 100

[app.client]
token = "Zb!2ku&eA2I6f&eP$s1lRIwj01mu9LU8"
server_ip = "127.0.0.1" # Replace with external/internal IPv4 address
server_port = 1060
nodes = ["127.0.0.1"] # Node IP list
node_timeout = 100

[app.load_balancer]
use_scaling = true # Allow/disallow the scaling (all the following options affected if enabled)
window_start_size_bits = 2 # 1=2, 2=4, 4=8 ... 8=256 and so on
window_max_size_bits = 8 # Same
scale_up_interval = 1 # When interacting with the payload  distributor - if the client made a request to it within the last N seconds, scale up
scale_down_interval = 2 # When interacting with the payload distributor - if the client made a request to for more than N seconds ago, scale down
